<?php

return [
    'cache_key' => 'rikms.platform_settings',
    'cache_ttl_seconds' => 300,

    'settings' => [
        'site.name' => [
            'type' => 'string',
            'default' => 'RIKMS v2',
            'group' => 'general',
            'label' => 'Site Name',
            'description' => 'Public and administrative platform name.',
            'is_public' => true,
            'operational' => false,
            'enforced' => true,
            'status' => 'informational',
        ],
        'site.short_name' => [
            'type' => 'string',
            'default' => 'RIKMS',
            'group' => 'general',
            'label' => 'Short Name',
            'description' => 'Short display name used in compact UI surfaces.',
            'is_public' => true,
            'operational' => false,
            'enforced' => true,
            'status' => 'informational',
        ],
        'site.default_language' => [
            'type' => 'string',
            'default' => 'English',
            'group' => 'general',
            'label' => 'Default Language',
            'description' => 'Default language label shown in the administration UI.',
            'is_public' => true,
            'operational' => false,
            'enforced' => false,
            'status' => 'informational',
        ],
        'site.timezone' => [
            'type' => 'string',
            'default' => 'Asia/Manila (UTC+8)',
            'group' => 'general',
            'label' => 'Timezone',
            'description' => 'Administrative timezone label. Server timezone remains deployment-managed.',
            'is_public' => true,
            'operational' => false,
            'enforced' => false,
            'status' => 'informational',
        ],
        'site.logo_url' => [
            'type' => 'string',
            'default' => null,
            'group' => 'general',
            'label' => 'Logo URL',
            'description' => 'Uploaded platform logo URL.',
            'is_public' => true,
            'operational' => false,
            'enforced' => true,
            'status' => 'informational',
        ],
        'uploads.max_file_size_mb' => [
            'type' => 'integer',
            'default' => 25,
            'min' => 1,
            'max' => 200,
            'group' => 'uploads',
            'label' => 'Maximum Upload Size',
            'description' => 'Maximum accepted PDF upload size, capped by PHP server upload limits.',
            'is_public' => false,
            'operational' => true,
            'enforced' => true,
            'status' => 'active',
        ],
        'uploads.allowed_file_types' => [
            'type' => 'json',
            'default' => ['PDF'],
            'group' => 'uploads',
            'label' => 'Allowed File Types',
            'description' => 'Allowed research upload file types. Current backend enforcement accepts PDF only.',
            'is_public' => false,
            'operational' => true,
            'enforced' => true,
            'status' => 'active',
        ],
        'research.default_status' => [
            'type' => 'string',
            'default' => 'draft',
            'options' => ['draft', 'published', 'pending-review'],
            'group' => 'research',
            'label' => 'Default Research Status',
            'description' => 'Default status for newly created agency research records.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'research.require_authors' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'research',
            'label' => 'Require Authors',
            'description' => 'Planned validation policy for research metadata.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'research.require_abstract' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'research',
            'label' => 'Require Abstract',
            'description' => 'Planned validation policy for research metadata.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'research.require_keywords' => [
            'type' => 'boolean',
            'default' => false,
            'group' => 'research',
            'label' => 'Require Keywords',
            'description' => 'Planned validation policy for research metadata.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'research.require_publication_year' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'research',
            'label' => 'Require Publication Year',
            'description' => 'Planned validation policy for research metadata.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'access_requests.enabled' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'access_control',
            'label' => 'Access Requests Enabled',
            'description' => 'Allow public users to submit access requests for restricted research.',
            'is_public' => true,
            'operational' => true,
            'enforced' => true,
            'status' => 'active',
            'environment_floor' => 'rikms.public_access_requests.enabled',
        ],
        'access_requests.default_policy' => [
            'type' => 'string',
            'default' => 'request-access',
            'options' => ['public', 'request-access', 'restricted'],
            'group' => 'access_control',
            'label' => 'Default Access Policy',
            'description' => 'Default access policy shown in repository settings. Research creation currently owns persisted access level.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'access_requests.embargo_override_enabled' => [
            'type' => 'boolean',
            'default' => false,
            'group' => 'access_control',
            'label' => 'Embargo Override',
            'description' => 'Planned policy for embargo access overrides.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'access_requests.embargo_duration_months' => [
            'type' => 'integer',
            'default' => 6,
            'min' => 1,
            'max' => 60,
            'group' => 'access_control',
            'label' => 'Embargo Duration',
            'description' => 'Planned default embargo duration.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'security.require_mfa_super_admins' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'security',
            'label' => 'Require MFA for Super Admins',
            'description' => 'Require two-factor authentication before Super Admin routes are available.',
            'is_public' => false,
            'operational' => true,
            'enforced' => true,
            'status' => 'active',
            'environment_floor' => 'rikms.security.force_super_admin_mfa',
        ],
        'security.login_alerts_enabled' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'security',
            'label' => 'Login Alerts',
            'description' => 'Security alert preference for authentication events.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'security.failed_login_threshold' => [
            'type' => 'integer',
            'default' => 5,
            'min' => 3,
            'max' => 20,
            'group' => 'security',
            'label' => 'Failed Login Threshold',
            'description' => 'Deployment-controlled authentication throttling remains handled by Laravel/Fortify.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'deployment_managed',
        ],
        'security.lockout_duration_minutes' => [
            'type' => 'integer',
            'default' => 15,
            'min' => 1,
            'max' => 240,
            'group' => 'security',
            'label' => 'Lockout Duration',
            'description' => 'Deployment-controlled authentication throttling remains handled by Laravel/Fortify.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'deployment_managed',
        ],
        'security.session_timeout_minutes' => [
            'type' => 'integer',
            'default' => 60,
            'min' => 5,
            'max' => 240,
            'group' => 'security',
            'label' => 'Session Timeout',
            'description' => 'Session timeout value used by the application session timeout middleware.',
            'is_public' => false,
            'operational' => true,
            'enforced' => true,
            'status' => 'active',
        ],
        'notifications.system_enabled' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'notifications',
            'label' => 'System Notifications',
            'description' => 'Notification preference defaults. User-level preferences still apply.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'notifications.email_enabled' => [
            'type' => 'boolean',
            'default' => false,
            'group' => 'notifications',
            'label' => 'Email Notifications',
            'description' => 'Email transport remains deployment-managed.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'deployment_managed',
        ],
        'notifications.security_alerts_enabled' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'notifications',
            'label' => 'Security Alerts',
            'description' => 'Planned global security notification toggle.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'notifications.access_request_submitted' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'notifications',
            'label' => 'Access Request Submitted',
            'description' => 'Planned global access-request notification toggle.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'notifications.research_published' => [
            'type' => 'boolean',
            'default' => true,
            'group' => 'notifications',
            'label' => 'Research Published',
            'description' => 'Planned global research-published notification toggle.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'notifications.weekly_activity_digest' => [
            'type' => 'boolean',
            'default' => false,
            'group' => 'notifications',
            'label' => 'Weekly Activity Digest',
            'description' => 'Planned scheduled digest toggle.',
            'is_public' => false,
            'operational' => true,
            'enforced' => false,
            'status' => 'deferred',
        ],
        'maintenance.enabled' => [
            'type' => 'boolean',
            'default' => false,
            'group' => 'maintenance',
            'label' => 'Maintenance Mode',
            'description' => 'Application-level maintenance gate that preserves Super Admin recovery access.',
            'is_public' => false,
            'operational' => true,
            'enforced' => true,
            'status' => 'active',
        ],
        'maintenance.notice_text' => [
            'type' => 'string',
            'default' => 'RIKMS is temporarily unavailable while maintenance is in progress.',
            'group' => 'maintenance',
            'label' => 'Maintenance Notice',
            'description' => 'Message displayed while application-level maintenance mode is enabled.',
            'is_public' => false,
            'operational' => false,
            'enforced' => true,
            'status' => 'informational',
        ],
        'backup.last_backup_at' => [
            'type' => 'string',
            'default' => 'Not configured',
            'group' => 'backup',
            'label' => 'Last Backup At',
            'description' => 'Backup status is informational until backup automation is configured.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'informational',
            'read_only' => true,
        ],
        'backup.frequency' => [
            'type' => 'string',
            'default' => 'Daily at 03:00 AM',
            'options' => ['Daily at 03:00 AM', 'Every 12 hours', 'Weekly on Sunday', 'Monthly on the 1st'],
            'group' => 'backup',
            'label' => 'Backup Frequency',
            'description' => 'Prepared backup schedule. It does not execute until backup automation is approved and enabled.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'preparation',
        ],
        'backup.destination_label' => [
            'type' => 'string',
            'default' => 'External drive',
            'max_length' => 100,
            'group' => 'backup',
            'label' => 'Backup Destination Label',
            'description' => 'Administrative label only. The real mount path remains server-managed.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'preparation',
        ],
        'backup.retention_days' => [
            'type' => 'integer',
            'default' => 30,
            'min' => 1,
            'max' => 365,
            'group' => 'backup',
            'label' => 'Backup Retention Days',
            'description' => 'Prepared retention policy. No backup files are deleted until automation is enabled.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'preparation',
        ],
        'backup.status' => [
            'type' => 'string',
            'default' => 'idle',
            'options' => ['idle', 'running', 'completed', 'failed'],
            'group' => 'backup',
            'label' => 'Backup Status',
            'description' => 'Backup status display value.',
            'is_public' => false,
            'operational' => false,
            'enforced' => false,
            'status' => 'informational',
            'read_only' => true,
        ],
        'ai.processing.enabled' => [
            'type' => 'boolean',
            'default' => false,
            'group' => 'ai',
            'label' => 'AI Processing Enabled',
            'description' => 'Allow new AI-assisted PDF parsing, metadata extraction, and SDG classification work.',
            'is_public' => false,
            'operational' => true,
            'enforced' => true,
            'status' => 'active',
        ],
    ],
];
